//Universal Types
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

//Exercise creator Types
export const SET_EXERCISE_FROM_BLUEPRINT = "SET_EXERCISE_FROM_BLUEPRINT";
export const SET_CURRENT_BLUEPRINT = "SET_CURRENT_BLUEPRINT";
export const SET_EXERCISE_NAME = "SET_EXERCISE_NAME";
export const SET_EXERCISE_TOP = "SET_EXERCISE_TOP";
export const CHANGE_EXERCISE_LEFT = "CHANGE_EXERCISE_LEFT";
export const CHANGE_EXERCISE_RIGHT = "CHANGE_EXERCISE_RIGHT";
export const CLEAR_CURRENT_BLUEPRINT = "CLEAR_CURRENT_BLUEPRINT";
export const CLEAR_CURRENT_EXERCISE = "CLEAR_CURRENT_EXERCISE";
export const GET_BLUEPRINTS_FROM_API = "GET_BLUEPRINTS_FROM_API";
export const POST_EXERCISE_TO_API = "POST_EXERCISE_TO_API";
//Blueprint creator Types
export const SET_BLUEPRINT_NAME = "SET_BLUEPRINT_NAME";
export const SET_BLUEPRINT_LEFT = "SET_BLUEPRINT_LEFT";
export const SET_BLUEPRINT_RIGHT = "SET_BLUEPRINT_RIGHT";
export const SET_BLUEPRINT_TOP = "SET_BLUEPRINT_TOP";
export const SET_BLUEPRINT_ERROR = "SET_BLUEPRINT_TOP";
export const CLEAR_BLUEPRINT_ERROR = "SET_BLUEPRINT_TOP";
export const POST_BLUEPRINT_TO_API = "POST_BLUEPRINT_TO_API";

//Exercise test types
export const SET_CURRENT_BLUEPRINT_FROM_API = "SET_BLUEPRINT_FROM_API";
export const SET_CURRENT_TEST_EXERCISE = "SET_CURRENT_TEST_EXERCISE";
export const GET_EXERCISE_FROM_API = "GET_EXERCISE_FROM_API";
export const POST_TEST_EXERCISE_TO_API_SUCCESS =
  "POST_TEST_EXERCISE_TO_API_SUCCESS";
export const POST_TEST_EXERCISE_TO_API_FAIL =
  "POST_TEST_EXERCISE_TO_API_SUCCESS";
//auth types
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//list types
export const GET_ALL_EXERCISES_FROM_API = "GET_ALL_EXERCISES_FROM_API";
export const DELETE_EXERCISES_FROM_API = "DELETE_EXERCISES_FROM_API";
export const DELETE_BLUEPRINT_FROM_API = "DELETE_BLUEPRINT_FROM_API";

//global types
export const CLEAR_ALL = "CLEAR_ALL";
